# https://github.com/marketplace/actions/sftp-uploader

name: SFTP

on:
  push:
    branches:
      - main

jobs:
  sftp:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: sftp
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          compress: true
          forceUpload: false
          localDir: '.'
          remoteDir: '/usi_safu/docs'
          exclude: '.git*,.DS_Store'
